### PR TITLE
Fix frame rate calculation using handler duration

### LINKED ISSUE #386: MP4 Incorrect Frame Rate from Snapchat Video
This issue likely pertains to most MP4 files independent of the source, but I have only tested on videos from Snapchat.

Below are the outputs of the FPS extracted from various tools

| Metadata-Extractor        | VLC           | Exiftool  | ffmpeg |
| :-------------: |:-------------:| :-----:|:--------:|
| 20.238      | 30.050836 | 30.051 | 30.05 |

Sample file:
[issue-386-snapchat.mp4.zip](https://github.com/drewnoakes/metadata-extractor/files/2769613/issue-386-snapchat.mp4.zip)

### PR DESCRIPTION
**Pull request by payton**
Fixes #386 

After fix, new frame rates as shown below (with sample file provided in corresponding issue):

| Metadata-Extractor        | VLC           | Exiftool  | ffmpeg |
| :-------------: |:-------------:| :-----:|:--------:|
| 30.051      | 30.050836 | 30.051 | 30.05 |

All frame rates in metadata-extractor-images remain the same.

### CODE REVIEW

File: Source/com/drew/metadata/mp4/boxes/TimeToSampleBox.java [hunk 1]
```diff
@@ -49,7 +49,14 @@ public TimeToSampleBox(SequentialReader reader, Box box) throws IOException
...
     public void addMetadata(Mp4VideoDirectory directory)
     {
-        float frameRate = (float) Mp4HandlerFactory.HANDLER_PARAM_TIME_SCALE/(float)entries.get(0).sampleDelta;
+        float sampleCount = 0;
+
+        for (EntryCount ec : entries) {
+            sampleCount += ec.sampleCount;
+        }
+
+        float frameRate = (float) Mp4HandlerFactory.HANDLER_PARAM_TIME_SCALE/((float) Mp4HandlerFactory.HANDLER_PARAM_DURATION / sampleCount);
```
Comment (drewnoakes) [inline Source/com/drew/metadata/mp4/boxes/TimeToSampleBox.java]: I assume `entries` will always have one item, otherwise we'll be dividing by zero.

**Comment by drewnoakes** [comment]
Thanks!
